# Generated by Django 3.2.18 on 2023-05-24 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigations', '0002_alter_uploadinvestigation_os_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.JSONField(null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macos_pstree_investigation', to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='PsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMM', models.TextField(null=True)),
                ('Offset', models.BigIntegerField(null=True)),
                ('PID', models.BigIntegerField(null=True)),
                ('PPID', models.BigIntegerField(null=True)),
                ('TID', models.BigIntegerField(null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macos_pslist_investigation', to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='Bash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.BigIntegerField(null=True)),
                ('Process', models.TextField(null=True)),
                ('CommandTime', models.TextField(null=True)),
                ('Command', models.CharField(max_length=500, null=True)),
                ('Tag', models.CharField(choices=[('Evidence', 'Evidence'), ('Suspicious', 'Suspicious')], max_length=11, null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macos_bash_investigation', to='investigations.uploadinvestigation')),
            ],
        ),
    ]
