# Generated by Django 3.2.18 on 2023-05-25 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0002_alter_uploadinvestigation_os_version'),
        ('macos_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check_syscall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Table_Address', models.TextField(null=True)),
                ('Table_Name', models.TextField(null=True)),
                ('Index', models.TextField(null=True)),
                ('Handler_Address', models.TextField(null=True)),
                ('Handler_Module', models.TextField(null=True)),
                ('Handler_Symbol', models.TextField(null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macos_check_syscall_investigation', to='investigations.uploadinvestigation')),
            ],
        ),
    ]
