# Generated by Django 3.2.18 on 2023-05-25 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macos_engine', '0002_check_syscall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check_syscall',
            old_name='Handler_Address',
            new_name='HandlerAddress',
        ),
        migrations.RenameField(
            model_name='check_syscall',
            old_name='Handler_Module',
            new_name='HandlerModule',
        ),
        migrations.RenameField(
            model_name='check_syscall',
            old_name='Handler_Symbol',
            new_name='HandlerSymbol',
        ),
        migrations.RenameField(
            model_name='check_syscall',
            old_name='Table_Address',
            new_name='TableAddress',
        ),
        migrations.RenameField(
            model_name='check_syscall',
            old_name='Table_Name',
            new_name='TableName',
        ),
    ]
