# Generated by Django 3.2.18 on 2023-05-25 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0002_alter_uploadinvestigation_os_version'),
        ('macos_engine', '0003_auto_20230525_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_syscall',
            name='Index',
            field=models.BigIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='VFSevents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(null=True)),
                ('PID', models.BigIntegerField(null=True)),
                ('Events', models.TextField(null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macos_vfsevents_investigation', to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='Socket_filters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Filter', models.TextField(null=True)),
                ('Name', models.TextField(null=True)),
                ('Member', models.TextField(null=True)),
                ('Socket', models.TextField(null=True)),
                ('Handler', models.TextField(null=True)),
                ('Module', models.TextField(null=True)),
                ('Symbol', models.TextField(null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macos_socket_filters_investigation', to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='Psaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.BigIntegerField(null=True)),
                ('Process', models.TextField(null=True)),
                ('Argc', models.BigIntegerField(null=True)),
                ('Arguments', models.BigIntegerField(null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macos_psaux_investigation', to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='Netstat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Offset', models.TextField(null=True)),
                ('Proto', models.TextField(null=True)),
                ('LocalIP', models.TextField(null=True)),
                ('LocalPort', models.BigIntegerField(null=True)),
                ('RemoteIP', models.TextField(null=True)),
                ('RemotePort', models.BigIntegerField(null=True)),
                ('State', models.TextField(null=True)),
                ('Process', models.TextField(null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macos_netstat_investigation', to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='Mount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device', models.TextField(null=True)),
                ('MountPoint', models.TextField(null=True)),
                ('Type', models.TextField(null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macos_mount_investigation', to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.BigIntegerField(null=True)),
                ('Process', models.TextField(null=True)),
                ('Start', models.TextField(null=True)),
                ('End', models.TextField(null=True)),
                ('Protection', models.TextField(null=True)),
                ('Map', models.TextField(null=True)),
                ('Name', models.TextField(null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macos_proc_maps_investigation', to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='Malfind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.BigIntegerField(null=True)),
                ('Process', models.TextField(null=True)),
                ('Start', models.TextField(null=True)),
                ('End', models.TextField(null=True)),
                ('Protection', models.TextField(null=True)),
                ('Hexdump', models.TextField(null=True)),
                ('Disasm', models.TextField(null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macos_malfind_investigation', to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='Lsof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileDescriptor', models.TextField(null=True)),
                ('FilePath', models.TextField(null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macos_lsof_investigation', to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='Lsmod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Offset', models.TextField(null=True)),
                ('Name', models.TextField(null=True)),
                ('Size', models.BigIntegerField(null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macos_lsmod_investigation', to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='List_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.TextField(null=True)),
                ('FilePath', models.TextField(null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macos_list_files_investigation', to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='Ifconfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Interface', models.TextField(null=True)),
                ('IPAddress', models.TextField(null=True)),
                ('MacAddress', models.TextField(null=True)),
                ('Promiscuous', models.TextField(null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macos_ifconfig_investigation', to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='Check_trap_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TableAddress', models.TextField(null=True)),
                ('TableName', models.TextField(null=True)),
                ('Index', models.BigIntegerField(null=True)),
                ('HandlerAddress', models.TextField(null=True)),
                ('HandlerModule', models.TextField(null=True)),
                ('HandlerSymbol', models.TextField(null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macos_check_trap_table_investigation', to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='Check_sysctl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(null=True)),
                ('Number', models.BigIntegerField(null=True)),
                ('Perms', models.TextField(null=True)),
                ('HandlerAddress', models.TextField(null=True)),
                ('Value', models.TextField(null=True)),
                ('HandlerModule', models.TextField(null=True)),
                ('HandlerSymbol', models.TextField(null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macos_check_sysctl_investigation', to='investigations.uploadinvestigation')),
            ],
        ),
    ]
