# Generated by Django 3.2.18 on 2023-05-25 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macos_engine', '0005_lsof_pid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maps',
            old_name='Map',
            new_name='MapName',
        ),
        migrations.RemoveField(
            model_name='maps',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='pslist',
            name='Offset',
        ),
        migrations.RemoveField(
            model_name='pslist',
            name='TID',
        ),
    ]
