# Generated by Django 3.2.18 on 2023-05-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macos_engine', '0006_auto_20230525_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psaux',
            name='Arguments',
            field=models.TextField(null=True),
        ),
    ]
