# Generated by Django 3.2.18 on 2023-05-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macos_engine', '0007_alter_psaux_arguments'),
    ]

    operations = [
        migrations.AddField(
            model_name='pslist',
            name='Offset',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pslist',
            name='TID',
            field=models.BigIntegerField(null=True),
        ),
    ]
