# Generated by Django 4.2.4 on 2023-08-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="case_bucket_id",
            field=models.UUIDField(),
        ),
    ]
