# Generated by Django 3.2.13 on 2022-06-13 13:39

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbols',
            name='symbols_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/k1nd0ne/Library/Python/3.8/lib/python/site-packages/volatility3/symbols'), upload_to=''),
        ),
    ]
