# Generated by Django 3.2.13 on 2022-06-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0002_alter_symbols_symbols_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbols',
            name='symbols_file',
            field=models.FileField(upload_to='symbols/uploads'),
        ),
    ]
