# Generated by Django 4.2.4 on 2024-03-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("symbols", "0002_rename_symbols_symbol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="symbol",
            name="symbols_file",
            field=models.FileField(upload_to="symbols/"),
        ),
    ]
