# Generated by Django 3.2.18 on 2023-05-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0003_alter_symbols_symbols_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbols',
            name='os',
            field=models.CharField(choices=[('Windows', 'Windows'), ('Linux', 'Linux'), ('MacOs', 'MacOs')], max_length=50),
        ),
    ]
