# Generated by Django 3.2.5 on 2022-01-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewIOC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('linkedInvestigation', models.CharField(max_length=100)),
                ('linkedInvestigationID', models.CharField(max_length=100)),
            ],
        ),
    ]
