# Generated by Django 3.2.12 on 2022-03-07 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0003_alter_uploadinvestigation_percentage'),
        ('iocs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newioc',
            name='linkedInvestigationID',
        ),
        migrations.AddField(
            model_name='newioc',
            name='context',
            field=models.CharField(default='n', max_length=255),
        ),
        migrations.AlterField(
            model_name='newioc',
            name='linkedInvestigation',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='investigations.uploadinvestigation'),
        ),
        migrations.AlterField(
            model_name='newioc',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newioc',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
