# Generated by Django 3.2.12 on 2022-03-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0003_alter_uploadinvestigation_percentage'),
        ('iocs', '0003_alter_newioc_context'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewIOC',
            new_name='IOC',
        ),
    ]
