# Generated by Django 3.2.12 on 2022-03-08 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0003_alter_uploadinvestigation_percentage'),
        ('iocs', '0005_alter_ioc_linkedinvestigation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ioc',
            name='linkedInvestigation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.uploadinvestigation'),
        ),
    ]
