# Generated by Django 3.2.13 on 2022-06-12 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('symbols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('count', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadInvestigation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('os_version', models.CharField(choices=[('Windows', 'Windows'), ('Linux', 'Linux')], max_length=50)),
                ('investigators', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=500)),
                ('status', models.CharField(max_length=20)),
                ('percentage', models.CharField(max_length=10)),
                ('taskid', models.CharField(max_length=500)),
                ('existingPath', models.CharField(max_length=500, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('eof', models.BooleanField()),
                ('uid', models.CharField(max_length=500)),
                ('linked_isf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='symbols.symbols')),
            ],
        ),
        migrations.CreateModel(
            name='ImageSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5', models.CharField(max_length=32, null=True)),
                ('sha1', models.CharField(max_length=40, null=True)),
                ('sha256', models.CharField(max_length=64, null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.uploadinvestigation')),
            ],
        ),
    ]
