# Generated by Django 3.2.5 on 2022-05-19 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('count', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadInvestigation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('os_version', models.CharField(choices=[('Windows', 'Windows')], max_length=50)),
                ('investigators', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=500)),
                ('status', models.CharField(max_length=20)),
                ('percentage', models.CharField(max_length=10)),
                ('taskid', models.CharField(max_length=500)),
                ('existingPath', models.CharField(max_length=500, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('eof', models.BooleanField()),
                ('uid', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Timeliner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plugin', models.CharField(max_length=500, null=True)),
                ('Description', models.CharField(max_length=500, null=True)),
                ('AccessedDate', models.CharField(max_length=500, null=True)),
                ('ChangedDate', models.CharField(max_length=500, null=True)),
                ('CreatedDate', models.CharField(max_length=500, null=True)),
                ('ModifiedDate', models.CharField(max_length=500, null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='TimeLineChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.JSONField(null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='Strings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('String', models.CharField(max_length=500, null=True)),
                ('PhysicalAddress', models.BigIntegerField(null=True)),
                ('Result', models.CharField(max_length=500, null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='SkeletonKeyCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.BigIntegerField(null=True)),
                ('Process', models.CharField(max_length=500, null=True)),
                ('SkeletonKeyFound', models.CharField(max_length=500, null=True)),
                ('rc4HmacInitialize', models.CharField(max_length=500, null=True)),
                ('rc4HmacDecrypt', models.CharField(max_length=500, null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='PsTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.JSONField(null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='PsScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.BigIntegerField(null=True)),
                ('PPID', models.BigIntegerField(null=True)),
                ('ImageFileName', models.CharField(max_length=255, null=True)),
                ('Offset', models.BigIntegerField(null=True)),
                ('Threads', models.BigIntegerField(null=True)),
                ('Handles', models.BigIntegerField(null=True)),
                ('SessionId', models.BigIntegerField(null=True)),
                ('Wow64', models.BooleanField()),
                ('CreateTime', models.CharField(max_length=255, null=True)),
                ('ExitTime', models.CharField(max_length=255, null=True)),
                ('Fileoutput', models.CharField(max_length=255, null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessDump',
            fields=[
                ('process_dump_id', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.BigIntegerField()),
                ('filename', models.CharField(max_length=255)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='Privs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.BigIntegerField(null=True)),
                ('Process', models.CharField(max_length=500, null=True)),
                ('Value', models.BigIntegerField(null=True)),
                ('Privilege', models.CharField(max_length=500, null=True)),
                ('Attributes', models.CharField(max_length=500, null=True)),
                ('Description', models.CharField(max_length=500, null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='NetStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Offset', models.BigIntegerField(null=True)),
                ('Proto', models.CharField(max_length=500, null=True)),
                ('LocalAddr', models.CharField(max_length=500, null=True)),
                ('LocalPort', models.CharField(max_length=500, null=True)),
                ('ForeignAddr', models.CharField(max_length=500, null=True)),
                ('ForeignPort', models.CharField(max_length=500, null=True)),
                ('State', models.CharField(max_length=500, null=True)),
                ('PID', models.BigIntegerField(null=True)),
                ('Owner', models.CharField(max_length=500, null=True)),
                ('Created', models.CharField(max_length=500, null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='NetScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Offset', models.BigIntegerField(null=True)),
                ('Proto', models.CharField(max_length=500, null=True)),
                ('LocalAddr', models.CharField(max_length=500, null=True)),
                ('LocalPort', models.CharField(max_length=500, null=True)),
                ('ForeignAddr', models.CharField(max_length=500, null=True)),
                ('ForeignPort', models.CharField(max_length=500, null=True)),
                ('State', models.CharField(max_length=500, null=True)),
                ('PID', models.BigIntegerField(null=True)),
                ('Owner', models.CharField(max_length=500, null=True)),
                ('Created', models.CharField(max_length=500, null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='NetGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.JSONField(null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='Malfind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.BigIntegerField(null=True)),
                ('Process', models.CharField(max_length=500, null=True)),
                ('StartVPN', models.BigIntegerField(null=True)),
                ('EndVPN', models.BigIntegerField(null=True)),
                ('Tag', models.CharField(max_length=500, null=True)),
                ('Protection', models.CharField(max_length=500, null=True)),
                ('CommitCharge', models.BigIntegerField(null=True)),
                ('PrivateMemory', models.BigIntegerField(null=True)),
                ('Fileoutput', models.CharField(max_length=500, null=True)),
                ('Hexdump', models.CharField(max_length=1000, null=True)),
                ('Disasm', models.CharField(max_length=1000, null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='Lsadump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Key', models.CharField(max_length=500, null=True)),
                ('Secret', models.CharField(max_length=1000, null=True)),
                ('Hex', models.CharField(max_length=500, null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='ImageSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5', models.CharField(max_length=32, null=True)),
                ('sha1', models.CharField(max_length=40, null=True)),
                ('sha256', models.CharField(max_length=64, null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='HiveList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileFullPath', models.CharField(max_length=500, null=True)),
                ('Offset', models.BigIntegerField(null=True)),
                ('Fileoutput', models.CharField(max_length=500, null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='Hashdump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=500, null=True)),
                ('rid', models.BigIntegerField(null=True)),
                ('lmhash', models.CharField(max_length=500, null=True)),
                ('nthash', models.CharField(max_length=500, null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='FileScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Offset', models.BigIntegerField(null=True)),
                ('Name', models.CharField(max_length=500, null=True)),
                ('Size', models.BigIntegerField(null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='FileDump',
            fields=[
                ('file_dump_id', models.AutoField(primary_key=True, serialize=False)),
                ('offset', models.BigIntegerField(null=True)),
                ('filename', models.CharField(max_length=255)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='Envars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.BigIntegerField(null=True)),
                ('Process', models.CharField(max_length=500, null=True)),
                ('Block', models.CharField(max_length=500, null=True)),
                ('Variable', models.CharField(max_length=500, null=True)),
                ('Value', models.CharField(max_length=500, null=True)),
                ('Description', models.CharField(max_length=500, null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='CmdLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.BigIntegerField(null=True)),
                ('Process', models.CharField(max_length=500, null=True)),
                ('Args', models.CharField(max_length=500, null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='Cachedump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500, null=True)),
                ('domain', models.CharField(max_length=500, null=True)),
                ('domain_name', models.CharField(max_length=500, null=True)),
                ('hash', models.CharField(max_length=500, null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.uploadinvestigation')),
            ],
        ),
    ]
