# Generated by Django 3.2.13 on 2022-05-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedump',
            name='domain',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cachedump',
            name='domain_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cachedump',
            name='hash',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cachedump',
            name='username',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cmdline',
            name='Args',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cmdline',
            name='Process',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='envars',
            name='Block',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='envars',
            name='Description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='envars',
            name='Process',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='envars',
            name='Value',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='envars',
            name='Variable',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='filescan',
            name='Name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='hashdump',
            name='User',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='hashdump',
            name='lmhash',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='hashdump',
            name='nthash',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='hivelist',
            name='FileFullPath',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='hivelist',
            name='Fileoutput',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='lsadump',
            name='Hex',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='lsadump',
            name='Key',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='malfind',
            name='Fileoutput',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='malfind',
            name='Process',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='malfind',
            name='Protection',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='malfind',
            name='Tag',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='netscan',
            name='Created',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='netscan',
            name='ForeignAddr',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='netscan',
            name='ForeignPort',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='netscan',
            name='LocalAddr',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='netscan',
            name='LocalPort',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='netscan',
            name='Owner',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='netscan',
            name='Proto',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='netscan',
            name='State',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='netstat',
            name='Created',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='netstat',
            name='ForeignAddr',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='netstat',
            name='ForeignPort',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='netstat',
            name='LocalAddr',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='netstat',
            name='LocalPort',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='netstat',
            name='Owner',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='netstat',
            name='Proto',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='netstat',
            name='State',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='privs',
            name='Attributes',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='privs',
            name='Description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='privs',
            name='Privilege',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='privs',
            name='Process',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='skeletonkeycheck',
            name='Process',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='skeletonkeycheck',
            name='SkeletonKeyFound',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='skeletonkeycheck',
            name='rc4HmacDecrypt',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='skeletonkeycheck',
            name='rc4HmacInitialize',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='strings',
            name='Result',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='strings',
            name='String',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='timeliner',
            name='AccessedDate',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='timeliner',
            name='ChangedDate',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='timeliner',
            name='CreatedDate',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='timeliner',
            name='Description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='timeliner',
            name='ModifiedDate',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='timeliner',
            name='Plugin',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
