# Generated by Django 3.2.12 on 2022-02-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadinvestigation',
            name='percentage',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
