# Generated by Django 3.2.18 on 2023-05-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadinvestigation',
            name='os_version',
            field=models.CharField(choices=[('Windows', 'Windows'), ('Linux', 'Linux'), ('MacOs', 'MacOs')], max_length=50),
        ),
    ]
