# Generated by Django 3.2.12 on 2022-02-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0002_uploadinvestigation_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadinvestigation',
            name='percentage',
            field=models.CharField(max_length=10),
        ),
    ]
