# Generated by Django 3.2.13 on 2022-06-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0003_auto_20220523_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadinvestigation',
            name='os_version',
            field=models.CharField(choices=[('Windows', 'Windows'), ('Linux', 'Linux')], max_length=50),
        ),
    ]
