# Generated by Django 3.2.13 on 2022-06-08 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0001_initial'),
        ('investigations', '0004_alter_uploadinvestigation_os_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadinvestigation',
            name='linked_isf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='symbols.symbols'),
        ),
    ]
