# Generated by Django 3.2.13 on 2022-06-08 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0001_initial'),
        ('investigations', '0005_uploadinvestigation_linked_isf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadinvestigation',
            name='linked_isf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='symbols.symbols'),
        ),
    ]
