# Generated by Django 5.1.1 on 2024-11-26 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("evidences", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrichedProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pid", models.IntegerField()),
                ("data", models.JSONField()),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evidences.evidence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VolatilityPlugin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(max_length=30, null=True)),
                ("description", models.TextField(null=True)),
                ("artefacts", models.JSONField(null=True)),
                ("category", models.CharField(max_length=100)),
                ("display", models.CharField(max_length=10)),
                ("results", models.BooleanField(default=False)),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evidences.evidence",
                    ),
                ),
            ],
        ),
    ]
