# Generated by Django 5.1.1 on 2024-10-11 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("evidences", "0003_alter_evidence_os"),
    ]

    operations = [
        migrations.CreateModel(
            name="VolatilityPlugin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("artefacts", models.JSONField(null=True)),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evidences.evidence",
                    ),
                ),
            ],
        ),
    ]
