# Generated by Django 5.1.1 on 2024-10-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volatility_engine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="volatilityplugin",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="volatilityplugin",
            name="icon",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
