# Generated by Django 5.1.1 on 2024-10-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "volatility_engine",
            "0002_volatilityplugin_description_volatilityplugin_icon",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="volatilityplugin",
            name="category",
            field=models.CharField(default="Null", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="volatilityplugin",
            name="display",
            field=models.CharField(default="Null", max_length=10),
            preserve_default=False,
        ),
    ]
