# Generated by Django 5.1.1 on 2024-11-21 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidences", "0006_alter_evidence_etag"),
        ("volatility_engine", "0004_volatilityplugin_results"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrichedProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pid", models.IntegerField()),
                ("data", models.JSONField()),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evidences.evidence",
                    ),
                ),
            ],
        ),
    ]
