# Generated by Django 5.1.1 on 2024-10-05 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0002_alter_case_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evidence",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
                ("etag", models.CharField(max_length=256)),
                (
                    "os",
                    models.CharField(
                        choices=[("Windows", "Windows"), ("Linux", "Linux")],
                        max_length=10,
                    ),
                ),
                ("status", models.IntegerField(default=0)),
                ("logs", models.JSONField(null=True)),
                ("access_key_id", models.TextField(null=True)),
                ("access_key", models.TextField(null=True)),
                ("url", models.TextField(null=True)),
                ("region", models.TextField(null=True)),
                ("endpoint", models.TextField(null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("AWS", "AWS"), ("MINIO", "MINIO")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "linked_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases.case"
                    ),
                ),
            ],
        ),
    ]
