# Generated by Django 5.1.1 on 2024-11-01 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("evidences", "0004_evidence_output_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evidence",
            name="output_path",
        ),
    ]
