# Generated by Django 5.1.1 on 2024-11-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidences", "0005_remove_evidence_output_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evidence",
            name="etag",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
