# Generated by Django 5.1.1 on 2024-11-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidences", "0007_alter_evidence_etag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evidence",
            name="etag",
            field=models.TextField(unique=True),
        ),
    ]
