# Generated by Django 5.1.1 on 2024-11-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidences", "0009_alter_evidence_etag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evidence",
            name="source",
            field=models.CharField(
                choices=[
                    ("AWS", "AWS"),
                    ("MINIO", "MINIO"),
                    ("FILESYSTEM", "FILESYSTEM"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
