# Generated by Django 5.1.1 on 2024-11-26 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("evidences", "0010_alter_evidence_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evidence",
            name="logs",
        ),
    ]
