# Generated by Django 4.2.4 on 2024-03-06 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("evidences", "0005_delete_imagesignature"),
    ]

    operations = [
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("artifact", "Artifact"),
                            ("directory", "Directory"),
                            ("process", "Process"),
                            ("file", "File"),
                        ],
                        max_length=100,
                    ),
                ),
                ("description", models.TextField()),
                ("value", models.TextField()),
                (
                    "tlp",
                    models.CharField(
                        choices=[
                            ("WHITE", "WHITE"),
                            ("GREEN", "GREEN"),
                            ("AMBER", "AMBER"),
                            ("AMBER+STRICT", "AMBER+STRICT"),
                            ("RED", "RED"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evidences.evidence",
                    ),
                ),
            ],
        ),
    ]
