# Generated by Django 4.2.4 on 2023-08-16 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesignature',
            name='investigation',
        ),
        migrations.RemoveField(
            model_name='memorydump',
            name='dump_linked_case',
        ),
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='ImageSignature',
        ),
        migrations.DeleteModel(
            name='MemoryDump',
        ),
    ]
