# Generated by Django 4.2.4 on 2024-03-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_indicator_id_alter_indicator_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="name",
            field=models.TextField(default="Name"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="indicator",
            name="type",
            field=models.CharField(
                choices=[
                    ("artifact-sha1", "Artifact - SHA-1"),
                    ("artifact-sha256", "Artifact - SHA-256"),
                    ("artifact-md5", "Artifact - MD5"),
                    ("artifact-url", "Artifact - URL"),
                    ("autonomous-system", "Autonomous System"),
                    ("directory", "Directory"),
                    ("domain-name", "Domain Name"),
                    ("email-addr", "Email Address"),
                    ("file-path", "File Path"),
                    ("file-sha256", "File SHA-256"),
                    ("file-sha1", "File SHA-1"),
                    ("file-md5", "File MD5"),
                    ("ipv4-addr", "IPv4 Address"),
                    ("ipv6-addr", "IPv6 Address"),
                    ("mac-addr", "MAC Address"),
                    ("mutex", "Mutex"),
                    ("network-traffic", "Network Traffic"),
                    ("process-name", "Process - Name"),
                    ("process-pid", "Process - PID"),
                    ("process-created", "Process - Created date"),
                    ("process-cwd", "Process - CWD"),
                    ("process-cmdline", "Process - Command Line"),
                    ("software", "Software"),
                    ("url", "URL"),
                    ("user-account", "User Account"),
                    ("windows-registry-key", "Windows Registry Key"),
                    ("x509-certificate", "X.509 Certificate"),
                ],
                max_length=100,
            ),
        ),
    ]
