# Generated by Django 4.2.4 on 2023-08-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_last_update',
            field=models.DateField(auto_now=True),
        ),
    ]
