# Generated by Django 3.2.13 on 2022-06-12 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linux_engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pslist',
            old_name='COM',
            new_name='COMM',
        ),
    ]
