# Generated by Django 3.2.13 on 2022-06-12 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0001_initial'),
        ('linux_engine', '0002_rename_com_pslist_comm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.BigIntegerField(null=True)),
                ('Process', models.CharField(max_length=255, null=True)),
                ('CommandTime', models.CharField(max_length=255, null=True)),
                ('Command', models.CharField(max_length=500, null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linux_bash_investigation', to='investigations.uploadinvestigation')),
            ],
        ),
    ]
