# Generated by Django 3.2.13 on 2022-06-13 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0001_initial'),
        ('linux_engine', '0004_procmaps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lsof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FD', models.BigIntegerField(null=True)),
                ('PID', models.BigIntegerField(null=True)),
                ('Path', models.CharField(max_length=255, null=True)),
                ('Process', models.CharField(max_length=500, null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linux_lsof_investigation', to='investigations.uploadinvestigation')),
            ],
        ),
    ]
