# Generated by Django 3.2.13 on 2022-06-13 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0001_initial'),
        ('linux_engine', '0006_ttycheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elfs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('End', models.BigIntegerField(null=True)),
                ('FilePath', models.CharField(max_length=255, null=True)),
                ('PID', models.BigIntegerField(null=True)),
                ('Process', models.CharField(max_length=255, null=True)),
                ('Start', models.BigIntegerField(null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linux_elfs_investigation', to='investigations.uploadinvestigation')),
            ],
        ),
    ]
