# Generated by Django 3.2.15 on 2022-12-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linux_engine', '0008_auto_20220917_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='pslist',
            name='TID',
            field=models.BigIntegerField(null=True),
        ),
    ]
