# Generated by Django 3.2.15 on 2022-12-27 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0001_initial'),
        ('linux_engine', '0010_pslist_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bash',
            name='CommandTime',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bash',
            name='Process',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='elfs',
            name='FilePath',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='elfs',
            name='Process',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lsof',
            name='Path',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='procmaps',
            name='FilePath',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='procmaps',
            name='Process',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pslist',
            name='COMM',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ttycheck',
            name='Module',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ttycheck',
            name='Name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ttycheck',
            name='Symbol',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='PsAux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ARGS', models.TextField(null=True)),
                ('COMM', models.BigIntegerField(null=True)),
                ('PID', models.BigIntegerField(null=True)),
                ('PPID', models.BigIntegerField(null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linux_psaux_investigation', to='investigations.uploadinvestigation')),
            ],
        ),
    ]
