# Generated by Django 3.2.15 on 2022-12-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linux_engine', '0011_auto_20221227_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psaux',
            name='COMM',
            field=models.TextField(null=True),
        ),
    ]
