# Generated by Django 3.2.15 on 2022-12-27 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0001_initial'),
        ('linux_engine', '0012_alter_psaux_comm'),
    ]

    operations = [
        migrations.CreateModel(
            name='MountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIELDS', models.TextField(null=True)),
                ('FSTYPE', models.TextField(null=True)),
                ('MAJOR_MINOR', models.TextField(max_length=20, null=True)),
                ('MNT_NS_ID', models.TextField(max_length=500, null=True)),
                ('MOUNTID', models.BigIntegerField(null=True)),
                ('MOUNT_OPTIONS', models.TextField(null=True)),
                ('MOUNT_POINT', models.TextField(null=True)),
                ('MOUNT_SRC', models.TextField(null=True)),
                ('PARENT_ID', models.BigIntegerField(null=True)),
                ('ROOT', models.TextField(null=True)),
                ('SB_OPTIONS', models.TextField(null=True)),
                ('Tag', models.CharField(choices=[('Evidence', 'Evidence'), ('Suspicious', 'Suspicious')], max_length=11, null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linux_mountinfo_investigation', to='investigations.uploadinvestigation')),
            ],
        ),
    ]
