# Generated by Django 3.2.15 on 2022-12-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linux_engine', '0013_mountinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='psaux',
            name='Tag',
            field=models.CharField(choices=[('Evidence', 'Evidence'), ('Suspicious', 'Suspicious')], max_length=11, null=True),
        ),
    ]
