# Generated by Django 3.2.18 on 2023-04-22 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0001_initial'),
        ('linux_engine', '0014_psaux_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sockstat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DestinationAddr', models.TextField(null=True)),
                ('DestinationPort', models.TextField(null=True)),
                ('FD', models.BigIntegerField(null=True)),
                ('Family', models.TextField(null=True)),
                ('Filter', models.TextField(null=True)),
                ('NetNS', models.TextField(null=True)),
                ('Pid', models.BigIntegerField(null=True)),
                ('Proto', models.TextField(null=True)),
                ('SockOffset', models.TextField(null=True)),
                ('SourceAddr', models.TextField(null=True)),
                ('State', models.TextField(null=True)),
                ('Type', models.TextField(null=True)),
                ('Tag', models.CharField(choices=[('Evidence', 'Evidence'), ('Suspicious', 'Suspicious')], max_length=11, null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linux_sockstat_investigation', to='investigations.uploadinvestigation')),
            ],
        ),
    ]
