# Generated by Django 3.2.18 on 2023-06-06 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0001_initial'),
        ('linux_engine', '0017_envars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeliner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plugin', models.TextField(null=True)),
                ('Description', models.TextField(null=True)),
                ('AccessedDate', models.TextField(null=True)),
                ('ChangedDate', models.TextField(null=True)),
                ('CreatedDate', models.TextField(null=True)),
                ('ModifiedDate', models.TextField(null=True)),
                ('Tag', models.CharField(choices=[('Evidence', 'Evidence'), ('Suspicious', 'Suspicious')], max_length=11, null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linux_timeliner_investigation', to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='TimeLineChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.JSONField(null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linux_timeline_investigation', to='investigations.uploadinvestigation')),
            ],
        ),
    ]
