# Generated by Django 4.2.16 on 2024-09-29 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bucket_id", models.UUIDField()),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("last_update", models.DateField(auto_now=True)),
                ("linked_users", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
