# Generated by Django 5.1.1 on 2024-10-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
