# Generated by Django 5.1.1 on 2024-11-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_alter_case_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="bucket_id",
            field=models.CharField(max_length=255),
        ),
    ]
