# Generated by Django 5.1.1 on 2024-11-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_alter_case_bucket_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="bucket_id",
            field=models.UUIDField(),
        ),
    ]
