# Generated by Django 5.1.1 on 2024-11-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0006_uploadsession"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="bucket_id",
        ),
        migrations.AlterField(
            model_name="case",
            name="name",
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
