# Generated by Django 4.2.11 on 2024-03-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("windows_engine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loot",
            name="Date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
