# Generated by Django 4.2.11 on 2024-04-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("windows_engine", "0002_loot_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loot",
            name="Date",
            field=models.DateField(auto_now=True),
        ),
    ]
