# Generated by Django 3.2.13 on 2022-06-28 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windows_engine', '0002_auto_20220612_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cachedump',
            old_name='domain',
            new_name='Domain',
        ),
        migrations.RenameField(
            model_name='cachedump',
            old_name='domain_name',
            new_name='Domainname',
        ),
        migrations.RenameField(
            model_name='cachedump',
            old_name='hash',
            new_name='Hash',
        ),
        migrations.RenameField(
            model_name='cachedump',
            old_name='username',
            new_name='Username',
        ),
    ]
