# Generated by Django 4.2.11 on 2024-04-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("windows_engine", "0003_alter_loot_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loot",
            name="Date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
