# Generated by Django 3.2.13 on 2022-07-04 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0001_initial'),
        ('windows_engine', '0003_auto_20220628_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAssist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Count', models.BigIntegerField(null=True)),
                ('FocusCount', models.BigIntegerField(null=True)),
                ('HiveName', models.TextField(null=True)),
                ('HiveOffset', models.BigIntegerField(null=True)),
                ('ID', models.TextField(null=True)),
                ('LastUpdated', models.TextField(null=True)),
                ('LastWriteTime', models.TextField(null=True)),
                ('Name', models.TextField(null=True)),
                ('Path', models.TextField(null=True)),
                ('RawData', models.TextField(null=True)),
                ('TimeFocused', models.TextField(null=True)),
                ('Type', models.TextField(null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows_userassist_investigation', to='investigations.uploadinvestigation')),
            ],
        ),
    ]
