# Generated by Django 3.2.13 on 2022-07-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows_engine', '0004_userassist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userassist',
            name='Count',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userassist',
            name='FocusCount',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userassist',
            name='HiveOffset',
            field=models.TextField(null=True),
        ),
    ]
