# Generated by Django 4.2.4 on 2023-11-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("windows_engine", "0004_getsids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="getsids",
            name="SID",
            field=models.TextField(null=True),
        ),
    ]
