# Generated by Django 3.2.13 on 2022-07-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows_engine', '0005_auto_20220704_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userassist',
            name='Count',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='userassist',
            name='FocusCount',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='userassist',
            name='HiveName',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='userassist',
            name='HiveOffset',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userassist',
            name='ID',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='userassist',
            name='LastWriteTime',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='userassist',
            name='Name',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='userassist',
            name='Path',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='userassist',
            name='RawData',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='userassist',
            name='TimeFocused',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='userassist',
            name='Type',
            field=models.BinaryField(null=True),
        ),
    ]
