# Generated by Django 4.2.4 on 2023-12-24 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("evidences", "0005_delete_imagesignature"),
        ("windows_engine", "0006_alter_cmdline_tag_alter_dlllist_tag_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Modules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Base", models.TextField(null=True)),
                ("Fileoutput", models.TextField(null=True)),
                ("Name", models.TextField(null=True)),
                ("Offset", models.TextField(null=True)),
                ("Path", models.TextField(null=True)),
                ("Size", models.BigIntegerField(null=True)),
                (
                    "Tag",
                    models.CharField(
                        choices=[
                            ("Evidence", "Evidence"),
                            ("Suspicious", "Suspicious"),
                            ("Clear", "Clear"),
                        ],
                        max_length=11,
                        null=True,
                    ),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="windows_modules_evidence",
                        to="evidences.evidence",
                    ),
                ),
            ],
        ),
    ]
