# Generated by Django 4.2.4 on 2023-12-24 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("evidences", "0005_delete_imagesignature"),
        ("windows_engine", "0007_modules"),
    ]

    operations = [
        migrations.CreateModel(
            name="SvcScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Binary", models.TextField(null=True)),
                ("Display", models.TextField(null=True)),
                ("Name", models.TextField(null=True)),
                ("Offset", models.TextField(null=True)),
                ("Order", models.TextField(null=True)),
                ("PID", models.BigIntegerField(null=True)),
                ("Start", models.TextField(null=True)),
                ("State", models.TextField(null=True)),
                ("Type", models.TextField(null=True)),
                (
                    "Tag",
                    models.CharField(
                        choices=[
                            ("Evidence", "Evidence"),
                            ("Suspicious", "Suspicious"),
                            ("Clear", "Clear"),
                        ],
                        max_length=11,
                        null=True,
                    ),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="windows_svcscan_evidence",
                        to="evidences.evidence",
                    ),
                ),
            ],
        ),
    ]
