# Generated by Django 3.2.13 on 2022-07-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows_engine', '0008_auto_20220712_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlllist',
            name='Process',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dlllist',
            name='Base',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dlllist',
            name='Name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dlllist',
            name='PID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dlllist',
            name='Path',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dlllist',
            name='Size',
            field=models.BigIntegerField(null=True),
        ),
    ]
