# Generated by Django 3.2.13 on 2022-07-12 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windows_engine', '0009_auto_20220712_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dlllist',
            old_name='File_output',
            new_name='Fileoutput',
        ),
    ]
