# Generated by Django 4.2.4 on 2024-01-10 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("evidences", "0005_delete_imagesignature"),
        ("windows_engine", "0009_ssdt"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.TextField()),
                ("Status", models.BooleanField()),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="windows_loot",
                        to="evidences.evidence",
                    ),
                ),
            ],
        ),
    ]
