# Generated by Django 3.2.13 on 2022-07-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows_engine', '0010_rename_file_output_dlllist_fileoutput'),
    ]

    operations = [
        migrations.AddField(
            model_name='handles',
            name='Process',
            field=models.TextField(null=True),
        ),
    ]
