# Generated by Django 4.2.4 on 2024-01-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("windows_engine", "0010_loot"),
    ]

    operations = [
        migrations.AddField(
            model_name="loot",
            name="FileName",
            field=models.TextField(default="test"),
            preserve_default=False,
        ),
    ]
