# Generated by Django 3.2.13 on 2022-08-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows_engine', '0011_handles_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedump',
            name='filename',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='processdump',
            name='filename',
            field=models.TextField(null=True),
        ),
    ]
