# Generated by Django 3.2.13 on 2022-08-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows_engine', '0012_auto_20220802_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='privs',
            name='Tag',
            field=models.CharField(choices=[('Evidence', 'Evidence'), ('Suspicious', 'Suspicious')], max_length=11, null=True),
        ),
    ]
