# Generated by Django 4.2.4 on 2024-01-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("windows_engine", "0012_alter_loot_filename"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processdump",
            name="dump_id",
        ),
        migrations.RenameField(
            model_name="pstree",
            old_name="graph",
            new_name="artefacts",
        ),
        migrations.RemoveField(
            model_name="psscan",
            name="CreateTime",
        ),
        migrations.RemoveField(
            model_name="psscan",
            name="ExitTime",
        ),
        migrations.RemoveField(
            model_name="psscan",
            name="Fileoutput",
        ),
        migrations.RemoveField(
            model_name="psscan",
            name="Handles",
        ),
        migrations.RemoveField(
            model_name="psscan",
            name="ImageFileName",
        ),
        migrations.RemoveField(
            model_name="psscan",
            name="Offset",
        ),
        migrations.RemoveField(
            model_name="psscan",
            name="PID",
        ),
        migrations.RemoveField(
            model_name="psscan",
            name="PPID",
        ),
        migrations.RemoveField(
            model_name="psscan",
            name="SessionId",
        ),
        migrations.RemoveField(
            model_name="psscan",
            name="Threads",
        ),
        migrations.RemoveField(
            model_name="psscan",
            name="Wow64",
        ),
        migrations.AddField(
            model_name="psscan",
            name="artefacts",
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name="FileDump",
        ),
        migrations.DeleteModel(
            name="ProcessDump",
        ),
    ]
