# Generated by Django 3.2.13 on 2022-08-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows_engine', '0014_auto_20220812_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='strings',
            name='Tag',
            field=models.CharField(choices=[('Evidence', 'Evidence'), ('Suspicious', 'Suspicious')], max_length=11, null=True),
        ),
    ]
