# Generated by Django 4.2.4 on 2024-02-25 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("evidences", "0005_delete_imagesignature"),
        ("windows_engine", "0015_remove_handles_grantedaccess_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MFTScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artefacts", models.JSONField(null=True)),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="windows_mftscan_evidence",
                        to="evidences.evidence",
                    ),
                ),
            ],
        ),
    ]
