# Generated by Django 3.2.13 on 2022-08-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows_engine', '0015_strings_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='filescan',
            name='Tag',
            field=models.CharField(choices=[('Evidence', 'Evidence'), ('Suspicious', 'Suspicious')], max_length=11, null=True),
        ),
    ]
