# Generated by Django 3.2.15 on 2022-12-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows_engine', '0018_ldrmodules'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldrmodules',
            name='Tag',
            field=models.CharField(choices=[('Evidence', 'Evidence'), ('Suspicious', 'Suspicious')], max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='ldrmodules',
            name='Process',
            field=models.TextField(null=True),
        ),
    ]
