# Generated by Django 3.2.18 on 2023-04-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows_engine', '0022_drivermodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivermodule',
            name='Tag',
            field=models.CharField(choices=[('Evidence', 'Evidence'), ('Suspicious', 'Suspicious')], max_length=11, null=True),
        ),
    ]
