# Generated by Django 3.2.18 on 2023-04-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windows_engine', '0025_vadwalk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='malfind',
            old_name='Tag',
            new_name='VTag',
        ),
    ]
