# Generated by Django 4.2.4 on 2023-08-17 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('dump_id', models.AutoField(primary_key=True, serialize=False)),
                ('dump_name', models.CharField(max_length=250)),
                ('dump_os', models.CharField(choices=[('Windows', 'Windows'), ('Linux', 'Linux')], max_length=10)),
                ('dump_linked_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
    ]
