# Generated by Django 4.2.4 on 2023-08-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='dump_status',
            field=models.IntegerField(default=0),
        ),
    ]
