# Generated by Django 4.2.4 on 2023-08-27 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evidences', '0002_evidence_dump_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5', models.CharField(max_length=32, null=True)),
                ('sha1', models.CharField(max_length=40, null=True)),
                ('sha256', models.CharField(max_length=64, null=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evidences.evidence')),
            ],
        ),
    ]
