# Generated by Django 4.2.11 on 2024-05-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidences', '0003_rename_dump_endpoint_evidence_dump_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='dump_endpoint',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='dump_region',
            field=models.TextField(null=True),
        ),
    ]
