# Generated by Django 4.2.4 on 2023-08-27 19:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("evidences", "0004_evidence_dump_etag"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ImageSignature",
        ),
    ]
