# Generated by Django 4.2.4 on 2024-03-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evidences", "0005_delete_imagesignature"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="dump_logs",
            field=models.JSONField(null=True),
        ),
    ]
