# Generated by Django 5.1.1 on 2024-11-26 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("evidences", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Indicator",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("artifact-sha1", "Artifact - SHA-1"),
                            ("artifact-sha256", "Artifact - SHA-256"),
                            ("artifact-md5", "Artifact - MD5"),
                            ("artifact-url", "Artifact - URL"),
                            ("autonomous-system", "Autonomous System"),
                            ("directory", "Directory"),
                            ("domain-name", "Domain Name"),
                            ("email-addr", "Email Address"),
                            ("file-path", "File Path"),
                            ("file-sha256", "File SHA-256"),
                            ("file-sha1", "File SHA-1"),
                            ("file-md5", "File MD5"),
                            ("ipv4-addr", "IPv4 Address"),
                            ("ipv6-addr", "IPv6 Address"),
                            ("mac-addr", "MAC Address"),
                            ("mutex", "Mutex"),
                            ("network-traffic", "Network Traffic"),
                            ("process-name", "Process - Name"),
                            ("process-cwd", "Process - CWD"),
                            ("process-cmdline", "Process - Command Line"),
                            ("software", "Software"),
                            ("url", "URL"),
                            ("user-account", "User Account"),
                            ("windows-registry-key", "Windows Registry Key"),
                            ("x509-certificate", "X.509 Certificate SHA1"),
                        ],
                        max_length=100,
                    ),
                ),
                ("description", models.TextField()),
                ("value", models.TextField()),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evidences.evidence",
                    ),
                ),
            ],
        ),
    ]
